import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Complaints and Compliments Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Complaints and Compliments Register
        </h1>
        <div className="w-full ">
          <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            <div className="mb-4">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="Name">
                Name
              </label>
              <input
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                  id="name" type="text" placeholder="Name"/>
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="password">
                Choose Feedback Category &nbsp; <span className='text-red-600'>*</span>
              </label>
              <select
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                  name="category">
                <option>Complaints</option>
                <option>Compliment</option>
              </select>
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="password">
                Choose School &nbsp; <span className='text-red-600'>*</span>
              </label>
              <select
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                  name='school'
              >
                <option value="1">Agriculture & Natural Resources</option>
                <option value="2">Arts & Social Sciences</option>
                <option value="3">Information Sciences	</option>
                <option value="4">Medicine</option>
                <option value="5">Nursing & Midewifery	</option>
                <option value="6">Public Health	</option>
                <option value="7">Tourism, Hospitality & Events Management	</option>
                <option value="8">Law</option>
                <option value="9">Biomedical Informatics	</option>
                <option value="10">Engineering	</option>
                <option value="11">Business & Economics	</option>
                <option value="12">Dentistry	</option>
                <option value="13">Education</option>
              </select>
            </div>
            <div className="mb-6">
              <label className="block text-gray-700 text-sm font-bold mb-2" htmlFor="password">
                Feedback Message  &nbsp; <span className='text-red-600'>*</span>
              </label>
              <textarea
                  className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                  name="message"
              >

              </textarea>
            </div>

            <div className="flex items-center justify-between">
              <button
                  className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                  type="button">
                Submit
              </button>
            </div>
          </form>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
